package(default_visibility = ["//visibility:public"])

load("//bazel:custom_library.bzl", "custom_cc_library")

custom_cc_library(
  name = "vm",
  srcs = [
    "VirtualMachine.cc",
  ],
  hdrs = [
    "VirtualMachine.hh",
  ],
)