package(default_visibility = ["//visibility:public"])

load("//bazel:custom_library.bzl", "custom_cc_library")

custom_cc_library(
  name = "types",
  srcs = [
    "Chunk.cc",
  ],
  hdrs = [
    "Argument.hh",
    "Chunk.hh",
    "CompilerOutput.hh",
    "CompilerScope.hh",
    "Literal.hh",
    "Local.hh",
    "Object.hh",
    "ObjectClass.hh",
    "ObjectClosure.hh",
    "ObjectInstance.hh",
    "ObjectInstanceMethod.hh",
    "ObjectMap.hh",
    "ObjectModule.hh",
    "ObjectNative.hh",
    "ObjectString.hh",
    "OpCode.hh",
    "SafeQueue.hh",
    "Upvalue.hh",
    "Value.hh",
  ]
)