package(default_visibility = ["//visibility:public"])

load("//bazel:custom_library.bzl", "custom_cc_library")

custom_cc_library(
  name = "types",
  srcs = [],
  hdrs = [
    "CompilerOutput.hh",
    "Object.hh",
    "OpCode.hh",
    "Value.hh",
  ]
)