package(default_visibility = ["//visibility:public"])

load("//bazel:custom_library.bzl", "custom_cc_library")

custom_cc_library(
  name = "math",
  srcs = [
    "ObjectMatrix.cc",
  ],
  hdrs = [
    "ObjectMatrix.hh",
  ],
  deps = [
    "//src/types:types",
  ]
)