package(default_visibility = ["//visibility:public"])

load("//bazel:glsl_library.bzl", "glsl_library")

glsl_library(
  name = "triangle_vert",
  shader = "triangle.vert"
)

glsl_library(
  name = "triangle_frag",
  shader = "triangle.frag"
)