package(default_visibility = ["//visibility:public"])

load("//bazel:glsl_library.bzl", "glsl_library")

glsl_library(
  name = "polygon_vert",
  shader = "polygon.vert"
)

glsl_library(
  name = "polygon_frag",
  shader = "polygon.frag"
)